const SERVER_ERROR = 500;
const NOT_FOUND = 404;
const BAD_REQUEST = 400;
const OK = 200;
const CREATED = 201;
const UNAUTHORIZED = 401;
const FORBIDDEN = 403;
const GATEWAY_TIMEOUT = 504

export { SERVER_ERROR, NOT_FOUND, BAD_REQUEST, OK, CREATED, UNAUTHORIZED, FORBIDDEN, GATEWAY_TIMEOUT }
