"use strict";
exports.__esModule = true;
exports.GATEWAY_TIMEOUT = exports.FORBIDDEN = exports.UNAUTHORIZED = exports.CREATED = exports.OK = exports.BAD_REQUEST = exports.NOT_FOUND = exports.SERVER_ERROR = void 0;
var SERVER_ERROR = 500;
exports.SERVER_ERROR = SERVER_ERROR;
var NOT_FOUND = 404;
exports.NOT_FOUND = NOT_FOUND;
var BAD_REQUEST = 400;
exports.BAD_REQUEST = BAD_REQUEST;
var OK = 200;
exports.OK = OK;
var CREATED = 201;
exports.CREATED = CREATED;
var UNAUTHORIZED = 401;
exports.UNAUTHORIZED = UNAUTHORIZED;
var FORBIDDEN = 403;
exports.FORBIDDEN = FORBIDDEN;
var GATEWAY_TIMEOUT = 504;
exports.GATEWAY_TIMEOUT = GATEWAY_TIMEOUT;
